import currencySymbolMap from "currency-symbol-map";

// Currency code to name mapping
export const currencyNames: Record<string, string> = {
  NGN: "Nigerian Naira",
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  INR: "Indian Rupee",
  SGD: "Singapore Dollar",
  HKD: "Hong Kong Dollar",
  NZD: "New Zealand Dollar",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Zloty",
  ZAR: "South African Rand",
  BRL: "Brazilian Real",
  MXN: "Mexican Peso",
  KRW: "South Korean Won",
  TRY: "Turkish Lira",
  RUB: "Russian Ruble",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  EGP: "Egyptian Pound",
  KES: "Kenyan Shilling",
  GHS: "Ghanaian Cedi",
  UGX: "Ugandan Shilling",
  TZS: "Tanzanian Shilling",
  ETB: "Ethiopian Birr",
  XOF: "West African CFA Franc",
  XAF: "Central African CFA Franc",
  MAD: "Moroccan Dirham",
  TND: "Tunisian Dinar",
  DZD: "Algerian Dinar",
  ZMW: "Zambian Kwacha",
  BWP: "Botswana Pula",
  MWK: "Malawian Kwacha",
  MZN: "Mozambican Metical",
  AOA: "Angolan Kwanza",
  MGA: "Malagasy Ariary",
  CDF: "Congolese Franc",
  RWF: "Rwandan Franc",
  SZL: "Swazi Lilangeni",
  LSL: "Lesotho Loti",
  NAD: "Namibian Dollar",
  SLL: "Sierra Leonean Leone",
  GMD: "Gambian Dalasi",
  GNF: "Guinean Franc",
  LRD: "Liberian Dollar",
  SLE: "Sierra Leonean Leone",
  XPF: "CFP Franc",
  KMF: "Comorian Franc",
  SCR: "Seychellois Rupee",
  MUR: "Mauritian Rupee",
  BIF: "Burundian Franc",
  DJF: "Djiboutian Franc",
  ERN: "Eritrean Nakfa",
  SDG: "Sudanese Pound",
  SSP: "South Sudanese Pound",
  SOS: "Somali Shilling",
  LYD: "Libyan Dinar",
  MRU: "Mauritanian Ouguiya",
  STN: "São Tomé and Príncipe Dobra",
  CVE: "Cape Verdean Escudo",
  THB: "Thai Baht",
  VND: "Vietnamese Dong",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  PHP: "Philippine Peso",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  NPR: "Nepalese Rupee",
  MMK: "Myanmar Kyat",
  KHR: "Cambodian Riel",
  LAK: "Laotian Kip",
  BND: "Brunei Dollar",
  FJD: "Fijian Dollar",
  PGK: "Papua New Guinean Kina",
  SBD: "Solomon Islands Dollar",
  VUV: "Vanuatu Vatu",
  TOP: "Tongan Paʻanga",
  WST: "Samoan Tala",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  BOB: "Bolivian Boliviano",
  PYG: "Paraguayan Guaraní",
  UYU: "Uruguayan Peso",
  VES: "Venezuelan Bolívar",
  GYD: "Guyanese Dollar",
  SRD: "Surinamese Dollar",
  BBD: "Barbadian Dollar",
  BZD: "Belize Dollar",
  JMD: "Jamaican Dollar",
  TTD: "Trinidad and Tobago Dollar",
  BMD: "Bermudian Dollar",
  BSD: "Bahamian Dollar",
  KYD: "Cayman Islands Dollar",
  CUP: "Cuban Peso",
  DOP: "Dominican Peso",
  HTG: "Haitian Gourde",
  XCD: "East Caribbean Dollar",
  AWG: "Aruban Florin",
  ANG: "Netherlands Antillean Guilder",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  RSD: "Serbian Dinar",
  BAM: "Bosnia-Herzegovina Convertible Mark",
  MKD: "Macedonian Denar",
  ALL: "Albanian Lek",
  ISK: "Icelandic Króna",
  MDL: "Moldovan Leu",
  UAH: "Ukrainian Hryvnia",
  BYN: "Belarusian Ruble",
  GEL: "Georgian Lari",
  AMD: "Armenian Dram",
  AZN: "Azerbaijani Manat",
  KZT: "Kazakhstani Tenge",
  KGS: "Kyrgystani Som",
  TJS: "Tajikistani Somoni",
  TMT: "Turkmenistani Manat",
  UZS: "Uzbekistani Som",
  AFN: "Afghan Afghani",
  IRR: "Iranian Rial",
  IQD: "Iraqi Dinar",
  ILS: "Israeli New Shekel",
  JOD: "Jordanian Dinar",
  LBP: "Lebanese Pound",
  SYP: "Syrian Pound",
  YER: "Yemeni Rial",
  OMR: "Omani Rial",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  QAR: "Qatari Rial",
  BTN: "Bhutanese Ngultrum",
  MOP: "Macanese Pataca",
  HNL: "Honduran Lempira",
  GTQ: "Guatemalan Quetzal",
  NIO: "Nicaraguan Córdoba",
  CRC: "Costa Rican Colón",
  PAB: "Panamanian Balboa",
};

// Comprehensive list of currencies with names
const currencyCodes = [
  "NGN",
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CAD",
  "CHF",
  "CNY",
  "INR",
  "SGD",
  "HKD",
  "NZD",
  "SEK",
  "NOK",
  "DKK",
  "PLN",
  "ZAR",
  "BRL",
  "MXN",
  "KRW",
  "TRY",
  "RUB",
  "AED",
  "SAR",
  "EGP",
  "KES",
  "GHS",
  "UGX",
  "TZS",
  "ETB",
  "XOF",
  "XAF",
  "MAD",
  "TND",
  "DZD",
  "ZMW",
  "BWP",
  "MWK",
  "MZN",
  "AOA",
  "MGA",
  "CDF",
  "RWF",
  "SZL",
  "LSL",
  "NAD",
  "SLL",
  "GMD",
  "GNF",
  "LRD",
  "SLE",
  "XPF",
  "KMF",
  "SCR",
  "MUR",
  "BIF",
  "DJF",
  "ERN",
  "SDG",
  "SSP",
  "SOS",
  "LYD",
  "MRU",
  "STN",
  "CVE",
  "THB",
  "VND",
  "IDR",
  "MYR",
  "PHP",
  "PKR",
  "BDT",
  "LKR",
  "NPR",
  "MMK",
  "KHR",
  "LAK",
  "BND",
  "FJD",
  "PGK",
  "SBD",
  "VUV",
  "TOP",
  "WST",
  "CLP",
  "COP",
  "PEN",
  "BOB",
  "PYG",
  "UYU",
  "VES",
  "GYD",
  "SRD",
  "BBD",
  "BZD",
  "JMD",
  "TTD",
  "BMD",
  "BSD",
  "KYD",
  "CUP",
  "DOP",
  "HTG",
  "XCD",
  "AWG",
  "ANG",
  "BGN",
  "HRK",
  "CZK",
  "HUF",
  "RON",
  "RSD",
  "BAM",
  "MKD",
  "ALL",
  "ISK",
  "MDL",
  "UAH",
  "BYN",
  "GEL",
  "AMD",
  "AZN",
  "KZT",
  "KGS",
  "TJS",
  "TMT",
  "UZS",
  "AFN",
  "IRR",
  "IQD",
  "ILS",
  "JOD",
  "LBP",
  "SYP",
  "YER",
  "OMR",
  "KWD",
  "BHD",
  "QAR",
  "BTN",
  "MOP",
  "HNL",
  "GTQ",
  "NIO",
  "CRC",
  "PAB",
];

// Remove duplicates and filter valid codes
const uniqueCodes = Array.from(new Set(currencyCodes));

export const allCurrencies = uniqueCodes
  .map((code) => {
    const symbol = currencySymbolMap(code) || code;
    const name = currencyNames[code] || code;
    return {
      code,
      symbol,
      name,
    };
  })
  .filter((currency) => currency.code);
